food-groups:
  list:
    - FRUIT
    - VEGETABLE
    - DAIRY
    - PULSES_TOFU_AND_NUTS
    - BEVERAGES
    - MEAT_FISH_AND_EGGS
    - FATS_AND_OILS
    - CONDIMENTS
    - SNACKS_BARS_AND_COOKIES
    - CONFECTIONERY_AND_SUGARS


spring:
  data:
    cassandra:
      port: 9143
      contact-points: 127.0.0.1
      keyspace-name: fodmap
  security:
    user:
      name: username
      password: password